name: ТестОпс Demo

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "TestOps service parameter. Leave blank"
        required: false
      ALLURE_USERNAME:
        description: "TestOps service parameter. Leave blank"
        required: false

env:
  ALLURE_ENDPOINT: https://demo.qatools.cloud
  ALLURE_PROJECT_ID: 531
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: allure-results

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Установить allurectl
        uses: allure-framework/setup-allurectl@v1

      - name: Запустить тесты через allurectl watch
        run: allurectl watch -- pytest tests/ -v --alluredir=allure-results